### ISSUE TITLE
[BUG] - Cannot install Tempo 3.9.0 APK on a Samsung J6 (Android 10) phone

### ISSUE THREAD

**Issue by benoit-smith** [CappielloAntonio/tempo#318]
## Describe the bug

The aforementioned phone fails to install the Tempo 3.9.0 APK file dowloaded from the GitHub repo.

## Expected behavior

App installed.

## To Reproduce

1. Uninstall any previous versions of Tempo from the phone.
2. Download the Tempo 3.9.0 APK file from the GitHub repo.
3. Click on it to install.
4. See the message "App not installed".

## Environment
 - Android device: Samsung J6
 - Android OS version: 10
 - App version: 3.9.0
 - Other relevant details: [e.g., specific network conditions, external dependencies]

**Comment by CappielloAntonio** [comment]
Hi, can you try again by downloading the new apk (same location)? 
I didn't increase the version number, but it should work now

**Comment by benoit-smith** [comment]
Thank you. I'm afraid it doesn't seem to fix the issue.
Could this be linked to the previously installed version (3.8.1) from F-Droid?

**Comment by somehuman60** [comment]
Same here. Can't update 3.8.1 to 3.9 on two of my phones. Use Obtanium to install update and the version number stay the same.

**Comment by Douloureux** [comment]
Did the certificate used to sign the APK change?

**Comment by vurtomatic** [comment]
> Same here. Can't update 3.8.1 to 3.9 on two of my phones. Use Obtanium to install update and the version number stay the same.

I had the same issue with Obtanium and the apk downloaded from the release page.

`App not installed as package conflicts with an existing package`

**Comment by CappielloAntonio** [comment]
Could you test this new release?
[app-tempo-release.zip](https://github.com/user-attachments/files/18285963/app-tempo-release.zip)

**Comment by vurtomatic** [comment]
> Could you test this new release? [app-tempo-release.zip](https://github.com/user-attachments/files/18285963/app-tempo-release.zip)

Still the same error unfortunately. This time the phone came up with a security warning (Play Store protection warning).

I selected "install anyway" and got the error again. Odd, I don't recall having update issue before.

**Comment by codenamek83** [comment]
I'm experiencing the same issue when trying to upgrade the app from version 3.8.1 to 3.9 on my Samsung A52. It shows the error: 'App not installed as package conflicts with an existing package.

**Comment by Douloureux** [comment]
I compared the signatures for the v3.8.1 and v3.9 APKs using [AppVerifier](https://github.com/soupslurpr/AppVerifier), and they both return different values.

For v3.8.1, it returns F1:D2:D1:07:59:AB:15:22:31:21:63:A5:65:CD:E1:7F:CA:C3:2C:93:59:9D:20:76:4C:70:99:35:9D:53:A9:EF
For v3.9.0, it returns 8E:52:6B:64:42:C1:7E:4A:D9:CB:36:54:C7:A1:FC:E3:24:5B:0C:BD:22:D9:A4:01:5C:E9:23:CE:6B:83:0E:24

Android will refuse to update an app if the APK is signed with a different key. To verify this, I checked the value for v3.6.0 and it returns the same value as v3.8.1, F1:D2:D1:07:59:AB:15:22:31:21:63:A5:65:CD:E1:7F:CA:C3:2C:93:59:9D:20:76:4C:70:99:35:9D:53:A9:EF. Something about the signing key has changed for v3.9.0, could you please check this?

**Comment by mrg358** [comment]
Samsung user. Uninstalling v3.8.1 and fresh installation of v3.9.0 doesn't resolve the issue. opening apk fails with "invalid package" notice.

**Comment by wizzard-uu** [comment]
Pixel user, same error as reported above.

**Comment by Szeraax** [comment]
Looking to install tempo for the 1st time. Can't install 3.9. I'm running Samsung A13 on Android v13. Not sure if I have 64bit or 32bit OS. 

My guess is that either my phone is 32 bit and this app requires 64 bit (less likely) or my employer MDM doesn't allow sideloading of APKs and I'll have to wait for this apk to be available on fdroid.

**Comment by ciori** [comment]
Do we have an update on this? I think there is still the same problem with the different signatures.

**Comment by JuanJotaErre** [comment]
Same problem, not working on my Samsung A13, 32bit device.
Uninstalling and reinstalling does not work for me, the error is "App not installed because it's not compatible with your device"
I'm guessing because it is a 32bit device. Is there a reason why this new update would be 64bit only?

**Comment by eddyizm** [comment]
Commenting over here since @JuanJotaErre reminded me that there were quite a few people who were not able to install after 3.9.0 dropped 32bit support. @ciori @Szeraax @mrg358 @wizzard-uu @Douloureux @codenamek83 @vurtomatic @somehuman60 

Added a 32bit build over in my fork after some testing https://github.com/eddyizm/tempo/releases/tag/v3.15.0
You will need to uninstall the old 3.8 since I am using completely different signing keys.
